site_name: Demo Seite von Vivienne
site_url: http://gbs.niederer.swiss/dta23/Vivienne
theme:
  name: material
  palette:
    scheme: slate
    primary: indigo
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
nav:
  - Home: index.md
  - Details: details.md
copyright: 'Version: ${BUILD_VERSION}'